// =============================================================================

export const AUTH_USER = 'auth/AUTH_USER';
export const AUTH_USER_SUCCESS = 'auth/AUTH_USER_SUCCESS';
export const SIGNUP_USER = 'auth/SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'auth/SIGNUP_USER_SUCCESS';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const FETCH_MESSAGE = 'fetch_message';


// =============================================================================

export const FETCH_AUTH = "app/FETCH_AUTH"
export const AUTH_CLEAR = "app/AUTH_CLEAR"

export const UPDATE_COLLECTION_STATS = "app/UPDATE_COLLECTION_STATS"

export const SHOW_APP_MENU = "app/SHOW_APP_MENU"
export const HIDE_APP_MENU = "app/HIDE_APP_MENU"

export const SHOW_APP_DRAWER = "app/SHOW_APP_DRAWER"
export const HIDE_APP_DRAWER = "app/HIDE_APP_DRAWER"

// =============================================================================

// Modals

export const SHOW_MODAL_TICKER_NEW = "app/SHOW_MODAL_TICKER_NEW"
export const HIDE_MODAL_TICKER_NEW = "app/HIDE_MODAL_TICKER_NEW"

export const SHOW_MODAL_PROXY_NEW = "app/SHOW_MODAL_PROXY_NEW"
export const HIDE_MODAL_PROXY_NEW = "app/HIDE_MODAL_PROXY_NEW"

// =============================================================================

// Tickers

export const CREATE_TICKER = "app/CREATE_TICKER";
export const CREATE_TICKER_SUCCESS = "app/CREATE_TICKER_SUCCESS";
export const DELETE_TICKER = "app/DELETE_TICKER";
export const DELETE_TICKER_SUCCESS = "app/DELETE_TICKER_SUCCESS";

export const SEARCH_TICKERS = "app/SEARCH_TICKERS";
export const SEARCH_TICKERS_SUCCESS = "app/SEARCH_TICKERS_SUCCESS";

export const LOAD_TICKER = "app/LOAD_TICKER";
export const LOAD_TICKER_SUCCESS = "app/LOAD_TICKER_SUCCESS";

export const UPDATE_TICKER = "app/UPDATE_TICKER";
export const UPDATE_TICKER_SUCCESS = "app/UPDATE_TICKER_SUCCESS";

export const CLEAR_CURRENT_TICKER = "app/CLEAR_CURRENT_TICKER";

export const UPDATE_TICKER_FILTERS = "app/UPDATE_TICKER_FILTERS";
export const RESET_TICKER_FILTERS = "app/RESET_TICKER_FILTERS";

export const UPDATE_TICKER_COLLECTION_SETTINGS = "app/UPDATE_TICKER_COLLECTION_SETTINGS";

export const LOAD_MORE_TICKERS = "app/LOAD_MORE_TICKERS";
export const LOAD_MORE_TICKERS_SUCCESS = "app/LOAD_MORE_TICKERS_SUCCESS";

export const UPDATE_TOTAL_TICKERS_PIXELS = "app/UPDATE_TOTAL_TICKERS_PIXELS";
export const UPDATE_TOTAL_SCROLLED_TICKERS_PIXELS = "app/UPDATE_TOTAL_SCROLLED_TICKERS_PIXELS";

// =============================================================================

// Videos

export const CREATE_VIDEO = "app/CREATE_VIDEO";
export const CREATE_VIDEO_SUCCESS = "app/CREATE_VIDEO_SUCCESS";
export const DELETE_VIDEO = "app/DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESS = "app/DELETE_VIDEO_SUCCESS";

export const SEARCH_VIDEOS = "app/SEARCH_VIDEOS";
export const SEARCH_VIDEOS_SUCCESS = "app/SEARCH_VIDEOS_SUCCESS";

export const LOAD_VIDEO = "app/LOAD_VIDEO";
export const LOAD_VIDEO_SUCCESS = "app/LOAD_VIDEO_SUCCESS";

export const UPDATE_VIDEO = "app/UPDATE_VIDEO";
export const UPDATE_VIDEO_SUCCESS = "app/UPDATE_VIDEO_SUCCESS";

export const CLEAR_CURRENT_VIDEO = "app/CLEAR_CURRENT_VIDEO";

export const UPDATE_VIDEO_FILTERS = "app/UPDATE_VIDEO_FILTERS";
export const RESET_VIDEO_FILTERS = "app/RESET_VIDEO_FILTERS";

export const UPDATE_VIDEO_COLLECTION_SETTINGS = "app/UPDATE_VIDEO_COLLECTION_SETTINGS";

export const LOAD_MORE_VIDEOS = "app/LOAD_MORE_VIDEOS";
export const LOAD_MORE_VIDEOS_SUCCESS = "app/LOAD_MORE_VIDEOS_SUCCESS";

export const UPDATE_TOTAL_VIDEOS_PIXELS = "app/UPDATE_TOTAL_VIDEOS_PIXELS";
export const UPDATE_TOTAL_SCROLLED_VIDEOS_PIXELS = "app/UPDATE_TOTAL_SCROLLED_VIDEOS_PIXELS";


// =============================================================================

// Proxies

export const CREATE_PROXY = "app/CREATE_PROXY";
export const CREATE_PROXY_SUCCESS = "app/CREATE_PROXY_SUCCESS";
export const DELETE_PROXY = "app/DELETE_PROXY";
export const DELETE_PROXY_SUCCESS = "app/DELETE_PROXY_SUCCESS";

export const SEARCH_PROXYS = "app/SEARCH_PROXYS";
export const SEARCH_PROXYS_SUCCESS = "app/SEARCH_PROXYS_SUCCESS";

export const LOAD_PROXY = "app/LOAD_PROXY";
export const LOAD_PROXY_SUCCESS = "app/LOAD_PROXY_SUCCESS";

export const UPDATE_PROXY = "app/UPDATE_PROXY";
export const UPDATE_PROXY_SUCCESS = "app/UPDATE_PROXY_SUCCESS";

export const CLEAR_CURRENT_PROXY = "app/CLEAR_CURRENT_PROXY";

export const UPDATE_PROXY_FILTERS = "app/UPDATE_PROXY_FILTERS";
export const RESET_PROXY_FILTERS = "app/RESET_PROXY_FILTERS";

export const UPDATE_PROXY_COLLECTION_SETTINGS = "app/UPDATE_PROXY_COLLECTION_SETTINGS";

export const LOAD_MORE_PROXYS = "app/LOAD_MORE_PROXYS";
export const LOAD_MORE_PROXYS_SUCCESS = "app/LOAD_MORE_PROXYS_SUCCESS";

export const UPDATE_TOTAL_PROXYS_PIXELS = "app/UPDATE_TOTAL_PROXYS_PIXELS";
export const UPDATE_TOTAL_SCROLLED_PROXYS_PIXELS = "app/UPDATE_TOTAL_SCROLLED_PROXYS_PIXELS";

export const UPDATE_PROXY_BANNED = "app/UPDATE_PROXY_BANNED"
export const UPDATE_PROXY_BANNED_SUCCESS = "app/UPDATE_PROXY_BANNED_SUCCESS"

export const UPDATE_PROXY_WORKING = "app/UPDATE_PROXY_WORKING"
export const UPDATE_PROXY_WORKING_SUCCESS = "app/UPDATE_PROXY_WORKING_SUCCESS"

export const TEST_PROXY = "app/TEST_PROXY"
export const TEST_PROXY_SUCCESS = "app/TEST_PROXY_SUCCESS"


// =============================================================================

// Scraping Search Results

export const START_SCRAPING_SEARCH_RESULTS = "app/START_SCRAPING_SEARCH_RESULTS";
export const START_SCRAPING_SEARCH_RESULTS_SUCCESS = "app/START_SCRAPING_SEARCH_RESULTS_SUCCESS";

export const STOP_SCRAPING_SEARCH_RESULTS = "app/STOP_SCRAPING_SEARCH_RESULTS";
export const STOP_SCRAPING_SEARCH_RESULTS_SUCCESS = "app/STOP_SCRAPING_SEARCH_RESULTS_SUCCESS";

export const PAUSE_SCRAPING_SEARCH_RESULTS = "app/PAUSE_SCRAPING_SEARCH_RESULTS";
export const PAUSE_SCRAPING_SEARCH_RESULTS_SUCCESS = "app/PAUSE_SCRAPING_SEARCH_RESULTS_SUCCESS";

export const LOAD_SCRAPING_SEARCH_RESULTS_STATUS = "app/LOAD_SCRAPING_SEARCH_RESULTS_STATUS";
export const LOAD_SCRAPING_SEARCH_RESULTS_STATUS_SUCCESS = "app/LOAD_SCRAPING_SEARCH_RESULTS_STATUS_SUCCESS";

export const UPDATE_CURRENT_CYCLE_SEARCH_RESULTS = "app/UPDATE_CURRENT_CYCLE_SEARCH_RESULTS";
export const UPDATE_PREVIOUS_CYCLE_SEARCH_RESULTS = "app/UPDATE_PREVIOUS_CYCLE_SEARCH_RESULTS";

export const UPDATE_TICKERS_SEARCH_RESULTS = "app/UPDATE_TICKERS_SEARCH_RESULTS";
export const UPDATE_VIDEOS_SEARCH_RESULTS = "app/UPDATE_VIDEOS_SEARCH_RESULTS";


